name: the real

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/wrapper-validation@v4

      - uses: gradle/actions/setup-gradle@v4.1.0
        with:
          arguments: clean build
      
      - run: ./collect.sh
      
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: collect